name: methylation-analysis-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-matrixstats
  - bioconductor-minfi
  - bioconductor-conumee
  - bioconductor-minfidata
  - r-rtsne
  - bioconductor-sva
  - r-tictoc
  - jupyter_client
  - r-irkernel
